### ISSUE TITLE
Clean up PR:s by delegating build to Travis

### ISSUE THREAD

**Issue by krawaller** [krawaller/jscomp#10]
One way to get away from the umpteen updated files would be to make travis build them instead.

In fact, we could have only code in master, and let Travis run gh-pages all on its own!

**Comment by fyrkant** [comment]
Hell yeah, awesome idea!

**Comment by fyrkant** [comment]
I think the easiest way to fix this would be to use netlify for both build and hosting! They have [free pro accounts for open source projects](https://www.netlify.com/pricing/).

**Comment by krawaller** [comment]
Hmm, netlify looks really sweet! Will investigate!

**Comment by krawaller** [comment]
replaced by new issue (#28), forgot about this one :P
