### ISSUE TITLE
Add description and website

### ISSUE THREAD

**Issue by ghost** [krawaller/jscomp#16]
You could add:
- Description: "A small site with a collection of demos, where each demo has a number of implementations across various JS frameworks."
- Website: http://blog.krawaller.se/jscomp/
Thank you for jscomp.

**Comment by krawaller** [comment]
You mean to README.md, for the benefits of people checking out the repo here on github?

**Comment by ghost** [comment]
No, I mean description/website field of github project.

You can see my jscomp fork repo details: https://github.com/pmros/jscomp.

**Comment by krawaller** [comment]
Oh, right! I've never noticed that functionality before :P

**Comment by krawaller** [comment]
Done!

**Comment by ghost** [comment]
Thank you!
