### ISSUE TITLE
New navigation structure

### ISSUE THREAD

**Issue by krawaller** [krawaller/jscomp#23]
So! Today me and colleague @Win14Therese got started on something I've wanted to do for a long time, namely **redo the site navigation** so that it is, well, less opaque.

We have now...

* split *home*, *demo* and *implementation* views into several "tabs", making it look far less cluttered
* completely skipped the breadcrumbs, instead we have...
* descriptive headlines with links to related parts throughout, as well as...
* home link in the top left corner
* added pages for the individual frameworks (info to be fleshed out)
* removed some needless babble
* removed the "code" tab from the implementations, now you can only view one single code file at a time. less confusing.

The next step is to let our company designer do his magic. But, before we do that, I'd love some feedback on the navigation and the content reordering. @fyrkant and @pmros, my trusted brothers-in-arms, what do you guys think? :)

**Comment by ghost** [comment]
Great! But I'd like a side by side comparation code. On the left side the actual implementation code and on the right side the others (you could use a selectbox). At the moment, the other implementations code is bellow. It's a slight but important difference.
Thank you.

**Comment by krawaller** [comment]
Hmm. Not sure side-by-side will work; note that only some code files are horisontally small, many take up the entire width of the app. I'm considering making all code files full width anyway, it looks a bit weird that they're different size. But, that's a designer question.

However - a dropdown is an excellent idea (thank you!!), the current way of just listing all files isn't really usable. So, I added the dropdown, but still have the file below the current one. Live now. How does this feel?

**Comment by fyrkant** [comment]
Maybe its just the lack of styling in the top menu part (or maybe it's the friday night wine?) but I feel a little lost when I click into a demo, like the react firebase demo and want to get back to the demos. It takes two click now, right? Back to the home page and then to the demos. Are breadcrumbs not cool anymore, did I miss a medium post or something? 😜 

Other than that I like it a lot!

**Comment by krawaller** [comment]
Well, I don't know about breadcrumbs in general, but MY breadcrumbs definitely weren't cool. :)

Yeah, you're right, it takes two clicks, and I've been annoyed myself for the same reason. Hmm. I'll revisit the breadcrumbs! Thanks for the inspiration! :)

**Comment by fyrkant** [comment]
I really wanted to embed **Chicago - You're the inspiration** but apparently you can't embed youtube in github comments?! Well well, you can't have it all I guess.

**Comment by krawaller** [comment]
Three more questions I don't know the answer to:

* How to deal with the dependencies? Right now they're still listed (under the only non-killed subheadline in the entire site) on the implementation info page. I could keep them where they are but tableify them, or make `package.json` a selectable file among the others. Or perhaps make a new `build` section where we show `package.json` along with eventual other configs. Or just remove the dependencies entirely, since interested parties can click to the github section anyway.
* Our vocabulary isn't very clear. In general, isn't a demo potentially synonymous with an implementation? I'm considering renaming demos to *apps*. Thoughts?
* The front page needs to communicate what the thing is all about. Having culled lots of crap from it made it better, but it needs to be better still, I think. How about showing one demo app running, and then next to it we show three stacked versions of a code file, rotating them out for each other at a convenient interval?

**Comment by krawaller** [comment]
Hmm, one way of addressing the frontpage could be to make the demo-framework table into the frontpage. That would help with @fyrkant's issue too!

**Comment by ghost** [comment]
Just a poor's man opinion about side-by-side:
Java Standard Style doesn't limit the length of your code lines  but most people are agree that lines longer than 80 or 100 characters are bad for readability. On the other hand, today many screens are wide enough to show 160 or 200 characters per line. I think it's a matter of CSS breakpoints.

**Comment by krawaller** [comment]
Hmm. You're right. Again. It'd be easy enough to put the comparison file below on smaller screen with media queries. Gonna do some experimenting!

**Comment by krawaller** [comment]
Ok @pmros, dropdown nav side by side is now live (although no media query stuff to make it different on small screens yet). It really does feel much better, thank you again! Is this sort of how you envisioned it?

![](https://dl.dropboxusercontent.com/u/2287145/jscomp/sidebyside.png)

**Comment by ghost** [comment]
It looks great! Although it would be nice if you could remove the 900px limit for side-by-side on big screens.

**Comment by krawaller** [comment]
Yeah, definitely. I should just add 900px maxlimit to *children* of the container, and then just exclude the code bit from that. Or something. I probably won't do anything about that until the designer has had his say, he might move things about some more.

**Comment by krawaller** [comment]
Tried to tackle the frontpage thing. Figured that the best way to explain that we have different demos with different implementations is to show it! How do you like this:

![](https://dl.dropboxusercontent.com/u/2287145/jscomp/newfrontpage.png)

**Comment by krawaller** [comment]
I first had the codefiles shifting in the stack with an animation, but that was annoying as h*ck so I removed it.

**Comment by krawaller** [comment]
I hid the dependencies from the implementation info tabs for now. Might simply expose the full `package.json` later. Or not.

**Comment by fyrkant** [comment]
I love the stacked code snippets! But maybe add som hover effect so when you hover a snippet it comes to the front, gets a light fill color and the library name, like REACT, is shown in big pretty letters? And you can click it to jump to the demo. I can hack a bit at it now if you want!

**Comment by krawaller** [comment]
Gut reaction is that it will be pretty messy, much like my animations. But I'd love to see some @fyrkant hacking, so go right ahead! :D

Although, hover won't work, since you'll immediately trigger a new hover on whatever is now in the position of the one you moved to the front. :P But perhaps click to move a piece of code to the front? Or, simpler still, click anywhere on the stack to "rotate" it one step?

**Comment by fyrkant** [comment]
Hehe, yeah probably a little bit messy, but at least I'll take a look at the code, it was so long ago since I did something with jscomp... 

Talking about messy, having these conversations in GH issues, should we make a gitter chat or something?

**Comment by ghost** [comment]
👍 Click and rotate (and random sort at start)
👍 Gitter

**Comment by fyrkant** [comment]
Created this: https://gitter.im/jscomptalk/

We can try it out and see if we like it.

**Comment by krawaller** [comment]
Gonna close this issue now, and start new ones as needed for the various specific issues. Thank you for all the input!
